### ISSUE TITLE
payeezy_js full example

### ISSUE THREAD

**Issue by jabrego** [payeezy/payeezy_js#4]
Hello,

I am new to the development using rest API and wanted to see if there are any full code examples that shows the full process of Generating the Token, making the authorization and purchasing?

Thanks for your time and patience,

Jorge

**Comment by nohup-atulparmar** [comment]
Hi Jorge, 

We have code to get toke and its located @http://s.codepen.io/payeezyjs/debug/yNvVyy?

**Comment by ahkelly** [comment]
I do not see the question Jorge asked answered, you closed it with a link that does not answer his question. The link only shows how to generate a token NOT make a transaction such as a payment request once you have received the token. Please post a complete code example rather than only half the equation. It would be mots helpful and appreciated.

**Comment by nohup-atulparmar** [comment]
You can use https://github.com/payeezy/payeezy_direct_API/tree/master/payeezy_node  for authorization &  purchase.

**Comment by nohup-atulparmar** [comment]
Let us know if you have any specific requirement

**Comment by ahkelly** [comment]
OK, Thank you for the reference, this is very helpful. I am unsure why this code is not also included here to make it easier for people to find this as I would never have though to look in the direct area. Thanks again for the link.

**Comment by nohup-atulparmar** [comment]
I have included the link in readme document for 'authorize' and 'purchase' transactions. thanks
